services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-mdopvm}"
    image: cybulde-data-processing
    platform: linux/amd64
    container_name: cybulde-data-processing-container
    environment: 
      - GOOGLE_APPLICATION_CREDENTIALS=./creds/cybully-project-da20e495ea8d.json
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USER_NAME:-nhatminh}"
        USER_ID: "${USER_ID:-1000}"
    volumes:
      - ./:/app/
      - ~/.config/gcloud/:/home/${USER_NAME:-nhatminh}/.config/gcloud
    ports:
      - 8888:8888

    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    ipc: host
    init: true