version: v5
data_local_save_dir: ./data/raw
dvc_remote_repo: https://github.com/mdop297/cybulde-data-versioning.git
dvc_data_folder: data/raw
github_user_name: mdop297
infrastructure:
  project_id: cybully-project
  zone: asia-southeast1-a
  network: default
github_access_token_secret_id: github-access-token
dataset_reader_manager:
  _target_: src.data_processing.dataset_readers.DatasetReaderManager
  dataset_readers:
    ghc:
      _target_: src.data_processing.dataset_readers.GHCDatasetReader
      dataset_dir: ./data/raw/ghc
      dataset_name: ghc
      gcp_project_id: cybully-project
      gcp_github_access_token_secret_id: github-access-token
      dvc_remote_repo: https://github.com/mdop297/cybulde-data-versioning.git
      github_user_name: mdop297
      version: v5
      dev_split_ratio: 0.3
    jtc:
      _target_: src.data_processing.dataset_readers.JigsawToxicCommentsDatasetReader
      dataset_dir: ./data/raw/jigsaw-toxic-comment
      dataset_name: jtc
      gcp_project_id: cybully-project
      gcp_github_access_token_secret_id: github-access-token
      dvc_remote_repo: https://github.com/mdop297/cybulde-data-versioning.git
      github_user_name: mdop297
      version: v5
      dev_split_ratio: 0.06
    twitter:
      _target_: src.data_processing.dataset_readers.TwitterDatasetReader
      dataset_dir: ./data/raw/twitter
      dataset_name: twitter
      gcp_project_id: cybully-project
      gcp_github_access_token_secret_id: github-access-token
      dvc_remote_repo: https://github.com/mdop297/cybulde-data-versioning.git
      github_user_name: mdop297
      version: v5
      dev_split_ratio: 0.3
      test_split_ratio: 0.2
  repartition: true
  available_memory: 4000000000.0
dataset_cleaner_manager:
  _target_: src.data_processing.dataset_cleaners.DatasetCleanerManager
  dataset_cleaners:
    stop_words:
      _target_: src.data_processing.dataset_cleaners.StopwordsDatasetCleaner
    lower_case:
      _target_: src.data_processing.dataset_cleaners.LowerCaseDatasetCleaner
    url:
      _target_: src.data_processing.dataset_cleaners.URLDatasetCleaner
    punctuation:
      _target_: src.data_processing.dataset_cleaners.PunctuationDatasetCleaner
      punctuation: '!"#$%&''()*+,-./:;<=>?@[\]^_`{|}~'
    non_letters:
      _target_: src.data_processing.dataset_cleaners.NonLettersDatasetCleaner
    new_line:
      _target_: src.data_processing.dataset_cleaners.NewLineCharacterDatasetCleaner
    non_ascii:
      _target_: src.data_processing.dataset_cleaners.NonASCIIDatasetCleaner
    referance:
      _target_: src.data_processing.dataset_cleaners.ReferenceToAccountDatasetCleaner
    re_tweet:
      _target_: src.data_processing.dataset_cleaners.ReTweetDatasetCleaner
    spell_correction:
      _target_: src.data_processing.dataset_cleaners.SpellCorrectionDatasetCleaner
      spell_correction_model:
        _target_: src.utils.utils.SpellCorrectionModel
        max_dictionary_edit_distance: 2
        prefix_length: 7
        count_threshold: 1
dask_cluster:
  _target_: dask_cloudprovider.gcp.GCPCluster
  n_workers: 2
  projectid: cybully-project
  zone: asia-southeast1-a
  network: default
  network_projectid: cybully-project
  machine_type: e2-medium
  source_image: projects/ubuntu-os-cloud/global/images/ubuntu-minimal-2004-focal-v20220203
  docker_image: asia-southeast1-docker.pkg.dev/cybully-project/cybully-artifacts/cybulde-data-processing:b6e4d819-99a2-4ee4-a675-78fe651e5b96
  docker_args: '--log-driver=gcplogs

    '
  extra_bootstrap:
  - gcloud auth configure-docker --quiet asia-southeast1-docker.pkg.dev
  ngpus: 0
  gpu_type: null
  filesystem_size: 50
  disk_type: pd-standard
  on_host_maintenance: TERMINATE
  worker_class: dask.distributed.Nanny
  worker_options:
    nthreads: 1
  env_vars: {}
  scheduler_options: {}
  silence_logs: null
  asynchronous: null
  security: true
  preemptible: false
  debug: true
  instance_labels: null
  service_account: ''
  service_account_credentials: null
processed_data_save_dir: gs://cybulde_bucket/data/processed/default_run
run_tag: default_run
docker_image_name: asia-southeast1-docker.pkg.dev/cybully-project/cybully-artifacts/cybulde-data-processing
docker_image_tag: b6e4d819-99a2-4ee4-a675-78fe651e5b96
